server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
ribbon:
  eureka:
    enabled: true
feign:
  hystrix:
    enabled: true
spring:
  application:
    name: oasis-api
  redis:
    host: 39.106.227.22
    port: 6379
    password: docker@redis.com11037
  elasticsearch:
    rest:
      uris: 39.105.94.200:9200
      username: elastic
      password: elastic.org147258369
logging:
  level:
    org:
      springframework: debug