server:
  port: 8081
  tomcat:
    basedir: logs
    accesslog:
      buffered: false
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://47.103.195.52:8080/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 39.106.227.22
    instance-id: ${eureka.instance.ip-address}:${server.port}
    hostname: iZ2ze11vyivzjlc2stc5s4Z
ribbon:
  eureka:
    enabled: true
feign:
  hystrix:
    enabled: true
spring:
  application:
    name: oasis-api
  redis:
    host: 39.106.227.22
    port: 6379
    password: docker@redis.com11037
  elasticsearch:
    rest:
      uris: 39.105.94.200:9200
      username: elastic
      password: elastic.org147258369
logging:
  level:
    org:
      springframework: debug