server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://47.103.195.52:8080/eureka/
ribbon:
  eureka:
    enabled: true

feign:
  hystrix:
    enabled: true


spring:
  application:
    name: oasis-api
  redis:
    host: 39.106.227.22
    port: 6379
  elasticsearch:
    rest:
      connection-timeout: 1s
      read-timeout: 30s
      uris: 47.103.195.52:9200